### ISSUE TITLE
Could you please provide the literature related to lDES-main program？

### ISSUE THREAD

**Issue by cdyy123** [niklauskun/LDES#1]
Could you please provide the literature related to lDES-main program？

**Comment by niklauskun** [comment]
Hi, the paper draft could be found on [arXiv](https://arxiv.org/abs/2201.03421). We are still working on it to extend the content. The detailed method is in this [paper](https://ieeexplore.ieee.org/abstract/document/9304081).

**Comment by cdyy123** [comment]
thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "niklauskun/LDES"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月18日(星期二) 晚上10:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [niklauskun/LDES] Could you please provide the literature related to lDES-main program？ (Issue #1)





 
Hi, the paper draft could be found on arXiv
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
